import { createContext, useContext, useState } from 'react';

export const translations = {
  th: {
    // Navbar
    nav_menu: 'เมนู',
    nav_events: 'อีเวนต์',
    nav_gallery: 'แกลเลอรี่',
    nav_lineup: 'ไลน์อัพ',
    nav_faq: 'คำถาม',
    nav_contact: 'ติดต่อ',
    nav_reserve: 'จองโต๊ะ',
    nav_book_now: 'จองเลย',

    // Hero
    hero_badge: 'ติดถนนสีลม · กรุงเทพฯ · ก่อตั้ง 2009',
    hero_tagline: 'สถานที่สำหรับผู้กล้าและผู้อยากรู้',
    hero_book: 'จองคืนนี้ ↗',
    hero_events: 'ดูอีเวนต์',

    // Events Preview
    events_eyebrow: 'เดือนนี้',
    events_title: 'คืนที่\nกำลังจะมา',
    events_all: 'ดูทั้งหมด →',
    events_access: 'เข้าร่วม →',

    // About
    about_eyebrow: 'พื้นที่',
    about_title: 'ลงไป\nข้างล่าง',
    about_body1: 'White Rabbit คือมากกว่าบาร์ — มันคือการดิ่งลงสู่โลกที่ดนตรี อัตลักษณ์ และความหรูหราชนกัน ตั้งอยู่ใจกลางสีลม ย่านที่พลุกพล่านที่สุดของกรุงเทพฯ',
    about_body2: 'เปิดรับทุกคน นิยามโดยไม่มีใคร',
    about_link: 'สำรวจพื้นที่ →',
    about_badge1: 'ติดถนนสีลม',
    about_badge2: 'กรุงเทพฯ, TH',

    // Pride
    pride_headline_pre: 'พื้นที่',
    pride_highlight: 'มีชีวิตชีวา',
    pride_headline_post: 'LGBTQ+ ที่สุดในกรุงเทพฯ',
    pride_sub: 'ยินดีต้อนรับทุกคน · เห็นคุณค่าทุกคน',

    // Marquee
    marquee_items: ['WHITE RABBIT', '·', 'ก่อนถึงสีลมซอย 2', '·', 'กรุงเทพฯ', '·', 'ก่อตั้ง 2009', '·', 'LGBTQ+ FRIENDLY', '·', 'เปิดทุกคืน', '·'],

    // Promo
    promo_eyebrow: 'คืนนี้เท่านั้น',
    promo_title: 'ดีลคืนนี้',
    promo_happy_tag: 'แฮปปี้ อาวร์',
    promo_happy_title: 'คอกเทล 2 แถม 1',
    promo_happy_detail: 'จ–พฤ · 20:00–22:00',
    promo_happy_desc: 'คอกเทลซิกเนเจอร์ราคาครึ่งหนึ่ง เริ่มต้นคืนได้อย่างดี',
    promo_happy_cta: 'จองโต๊ะ',
    promo_fri_tag: 'ศุกร์พิเศษ',
    promo_fri_title: 'ฟรีช็อตเมื่อเข้าร้าน',
    promo_fri_detail: 'ทุกวันศุกร์ · พร้อมจองโต๊ะ',
    promo_fri_desc: 'จองโต๊ะก่อนเที่ยงคืน รับช็อตต้อนรับฟรีทันที',
    promo_fri_cta: 'จองเลย',
    promo_wknd_tag: 'วันหยุด',
    promo_wknd_title: 'แพ็กเกจขวด',
    promo_wknd_detail: 'ศุกร์–เสาร์ · เริ่ม ฿3,500',
    promo_wknd_desc: 'สุราพรีเมียม + มิกเซอร์ + โต๊ะจอง 4 ที่นั่ง จำนวนจำกัดต่อคืน',
    promo_wknd_cta: 'รับดีล',

    // Promos
    promo1_tag: 'แฮปปี้ อาวร์',
    promo1_title: 'Chang 3 แถม 1 ฟรี',
    promo1_detail: '15:00–20:00 · ทุกวัน',
    promo1_desc: 'ซื้อเบียร์ Chang 3 ขวด ฟรี 1 ขวด — เริ่มคืนได้ไวขึ้น',
    promo1_cta: 'จองโต๊ะ',
    promo2_tag: 'แฮปปี้ อาวร์',
    promo2_title: 'Singha Lite 4 ขวด ฿299',
    promo2_detail: '15:00–20:00 · ทุกวัน',
    promo2_desc: 'ซื้อเบียร์ Singha Lite 4 ขวด ในราคาเพียง 299 บาท',
    promo2_cta: 'จองเลย',
    promo3_tag: 'พุธพิเศษ',
    promo3_title: 'เบียร์สด Chang 3 แถม 1',
    promo3_detail: 'พุธ · ก่อนเที่ยงคืน',
    promo3_desc: 'ซื้อเบียร์สด Chang 3 แก้ว ฟรี 1 แก้ว — คืนวันพุธสุดคุ้ม',
    promo3_cta: 'รับดีล',
    promo4_tag: 'พุธพิเศษ',
    promo4_title: 'Chang Tower 2 แถม 1',
    promo4_detail: 'พุธ · ตลอดคืน',
    promo4_desc: 'ซื้อเบียร์สด Chang 2 Tower ฟรี 1 Tower — เอาไปเลย',
    promo4_cta: 'รับดีล',
    promo5_tag: 'ทุกวัน',
    promo5_title: 'Paladin Prosecco 2 ขวด ฿3,500',
    promo5_detail: 'ทุกวัน · จำนวนจำกัด',
    promo5_desc: 'ซื้อ Paladin Prosecco 2 ขวด ในราคา 3,500 บาท — ฉลองทุกคืน',
    promo5_cta: 'จองเลย',
    promo6_tag: 'สิทธิพิเศษวันเกิด',
    promo6_title: 'ลด 10% ในวันเกิดคุณ',
    promo6_detail: 'แสดงบัตร · ทุกวัน',
    promo6_desc: 'แสดงบัตรประชาชนในวันเกิด รับส่วนลด 10% ทันที 🎂',
    promo6_cta: 'จองคืนนี้',

    // Singers / Weekly Lineup
    singers_eyebrow: 'เสียงแห่งราตรี',
    singers_title: 'นักร้อง\nประจำ',
    singers_book: 'จองคืนนี้ →',
    lineup_sub: 'การแสดงสดทุกคืน · WHITE RABBIT BAR',
    events_h1: 'อีเวนต์',

    // Reviews
    reviews_eyebrow: 'เสียงจากลูกค้า',
    reviews_title: 'พวกเขา\nพูดว่า',
    reviews_count: '200+ รีวิว',

    // Map
    map_eyebrow: 'หาเราเจอ',
    map_title: 'มาหา\nเราได้เลย',
    map_address_label: 'ที่อยู่',
    map_hours_label: 'เวลาทำการ',
    map_transit_label: 'การเดินทาง',
    map_address_value: 'ติดถนนสีลม ก่อนถึงซอย 2\nกรุงเทพฯ 10500, ไทย',
    map_hours_value: 'ทุกวัน 15:00–LATE',
    map_transit_value: 'BTS ศาลาแดง (ทางออก 3)\nเดิน 3 นาที ร้านอยู่ก่อนถึงซอย 2',
    map_open_maps: 'เปิดใน Google Maps ↗',
    map_book: 'จองโต๊ะ →',

    // Reserve page
    reserve_eyebrow: 'พอร์ทัล',
    reserve_title: 'จองโต๊ะ',
    reserve_subtitle: 'กรอกฟอร์ม หรือติดต่อผ่าน LINE / โทรศัพท์ได้เลย เราจะยืนยันภายใน 24 ชั่วโมง',
    reserve_line_btn: 'ไลน์หาเรา',
    reserve_call_btn: 'โทรหาเรา',
    reserve_or: 'หรือกรอกฟอร์ม',
    reserve_name: 'ชื่อ-นามสกุล',
    reserve_email: 'อีเมล',
    reserve_phone: 'เบอร์โทร',
    reserve_date: 'วันที่',
    reserve_guests: 'จำนวนผู้เข้าร่วม',
    reserve_event: 'อีเวนต์',
    reserve_notes: 'หมายเหตุ',
    reserve_notes_ph: 'คำขอพิเศษ, โอกาสพิเศษ...',
    reserve_submit: 'ยืนยันการจอง →',
    reserve_walkin: 'รับ Walk-in · มีบริการเสิร์ฟที่โต๊ะ',
    reserve_confirmed_title: 'ยืนยัน\nแล้ว',
    reserve_confirmed_msg: 'เราได้รับคำขอจอง',
    reserve_confirmed_body: 'ทีมงานจะยืนยันการจองผ่านอีเมล',
    reserve_back: '← กลับหน้าหลัก',
    reserve_guest_singular: 'ท่าน',
    reserve_guest_plural: 'ท่าน',

    // FAQ
    faq_eyebrow: 'คำถามที่พบบ่อย',
    faq_subtitle: 'คำถามที่พบบ่อย — หากยังมีข้อสงสัย ติดต่อเราได้ที่ LINE หรืออีเมลด้านล่าง',
    faq_still: 'ยังมีคำถาม?',
    faq_contact_sub: 'ติดต่อเราได้โดยตรง',

    // Contact
    contact_eyebrow: 'ติดต่อเรา',
    contact_title: 'ติดต่อ',

    // Footer
    footer_tagline: 'ตามกระต่ายขาวลงไปในโพรง',
    footer_contact: 'ติดต่อ',
    footer_hours: 'เวลาทำการ',
    footer_copy: '© 2026 WHITE RABBIT BAR. สงวนลิขสิทธิ์',

    // Footer address & hours
    footer_address: 'ติดถนนสีลม ก่อนถึงซอย 2, กรุงเทพฯ 10500',
    footer_hours_1_day: 'ทุกวัน',
    footer_hours_1_time: '15:00–LATE',
    footer_hours_2_day: '',
    footer_hours_2_time: '',
    footer_hours_3_day: '',
    footer_hours_3_time: '',

    // Contact page
    contact_phone_label: 'โทรศัพท์',
    contact_phone_cta: 'โทรเลย',
    contact_line_label: 'ไลน์',
    contact_line_cta: 'เปิดไลน์',
    contact_location_label: 'ที่ตั้ง',
    contact_location_value: 'ติดถนนสีลม ก่อนถึงซอย 2, กรุงเทพฯ 10500',
    contact_location_cta: 'เปิดแผนที่',
    contact_hours_title: 'เวลาทำการ',
    contact_hours_1_day: 'ทุกวัน',
    contact_hours_1_time: '15:00 – LATE',
    contact_hours_2_day: '',
    contact_hours_2_time: '',
    contact_hours_3_day: '',
    contact_hours_3_time: '',
    contact_directions: 'เส้นทาง',
    contact_follow: 'ติดตามเรา',

    // Events page
    events_page_title: 'อีเวนต์\n& DJ NIGHTS',
    event1_desc: 'การเดินทางผ่านมินิมอลเทคโนและดาร์กเฮาส์ เมื่อเบสพูด มีแค่กำแพงที่ยังอยู่',
    event2_desc: 'อิเล็กทรอนิกส์แอมเบียนต์ผสมกับบีทใต้ดิน การทำสมาธิในการเคลื่อนไหว',
    event3_desc: 'เมื่อจังหวะพบกับสถาปัตยกรรม เสียงอินดัสเทรียลในพื้นที่ที่ใกล้ชิด',
    event4_desc: 'สุดยอดงาน Pride ฉลองอัตลักษณ์ผ่านดนตรีที่ไม่มีพรมแดน',
    event5_desc: 'ลึกใต้เมือง ดนตรีที่สั่นสะเทือนผ่านคอนกรีตและกระดูก',

    // FAQ questions & answers
    faq_q1: 'ร้านเปิด-ปิดกี่โมง?',
    faq_a1: 'ทุกวัน: 15:00 น. – จนดึก (LATE)',
    faq_q2: 'เดินทางมาที่ร้านอย่างไร?',
    faq_a2: 'ร้านอยู่ติดถนนสีลม ก่อนถึงซอย 2 ลง BTS ศาลาแดง ทางออก 3 แล้วเดิน 3 นาที จะเห็นร้านอยู่ริมถนน',
    faq_q3: 'มีการจองโต๊ะหรือไม่?',
    faq_a3: 'มีบริการจองโต๊ะ แนะนำให้จองล่วงหน้าเพื่อความสะดวก สามารถจองผ่านเว็บไซต์หรือติดต่อผ่าน LINE Official Account',
    faq_q4: 'มีค่าเข้าหรือไม่?',
    faq_a4: 'ปกติไม่มีค่าเข้า แต่บางคืนพิเศษหรืออีเวนต์อาจมีค่าเข้า กรุณาตรวจสอบตารางกิจกรรม',
    faq_q5: 'ร้านเป็น LGBTQ+ Friendly หรือไม่?',
    faq_a5: 'ใช่ครับ White Rabbit เป็นพื้นที่ปลอดภัยและเปิดกว้างสำหรับทุกคน ทุกเพศ ทุกอัตลักษณ์ ทุกคนได้รับการต้อนรับที่นี่',
    faq_q6: 'มีการแสดงสดหรือไม่?',
    faq_a6: 'มีการแสดงสดจากนักร้องและ DJ ทุกสัปดาห์ ดูรายละเอียดได้ที่หน้า Events',
    faq_q7: 'มีบริการที่จอดรถหรือไม่?',
    faq_a7: 'ไม่มีที่จอดรถของร้านโดยตรง แนะนำให้ใช้ BTS หรือ Grab/Taxi เพื่อความสะดวก',
    faq_q8: 'มีอาหารให้บริการหรือไม่?',
    faq_a8: 'เราเน้นเครื่องดื่มและค็อกเทลเป็นหลัก แต่มีของว่างและอาหารเบาๆ ให้บริการ',

    // Menu page
    menu_price_note: 'ราคาทั้งหมดในหน่วยบาท · ยังไม่รวม VAT 7% และ SERVICE CHARGE 10%',
    menu_thai_label1: 'ส้มตำ · เนื้อย่าง · หมึกย่าง · ยำ · แกง',

    // Footer / sticky
    sticky_book: 'จองเลย',
    scroll_label: 'เลื่อนลง',
  },

  en: {
    nav_menu: 'MENU',
    nav_events: 'EVENTS',
    nav_gallery: 'GALLERY',
    nav_lineup: 'LINE UP',
    nav_faq: 'FAQ',
    nav_contact: 'CONTACT',
    nav_reserve: 'RESERVE',
    nav_book_now: 'BOOK NOW',

    hero_badge: 'ON SILOM ROAD · BANGKOK · EST. 2019',
    hero_tagline: 'FOLLOW THE WHITE RABBIT DOWN THE HOLE.',
    hero_book: 'RESERVE A TABLE ↗',
    hero_events: "TONIGHT'S LINEUP",

    events_eyebrow: 'THIS YEAR',
    events_title: 'UPCOMING\nNIGHTS',
    events_all: 'ALL EVENTS →',
    events_access: 'ACCESS →',

    about_eyebrow: 'THE SPACE',
    about_title: 'DOWN\nTHE\nHOLE',
    about_body1: 'White Rabbit is more than a bar — it\'s a descent into a world where music, identity, and luxury collide. Nestled in the heart of Silom, Bangkok\'s most electric neighborhood.',
    about_body2: 'Open to all. Defined by none.',
    about_link: 'EXPLORE THE SPACE →',
    about_badge1: 'ON SILOM ROAD',
    about_badge2: 'BANGKOK, TH',

    pride_headline_pre: 'Bangkok\'s most',
    pride_highlight: 'vibrant',
    pride_headline_post: 'LGBTQ+ space.',
    pride_sub: 'ALL ARE WELCOME · ALL ARE SEEN',

    marquee_items: ['WHITE RABBIT', '·', 'BEFORE SILOM SOI 2', '·', 'BANGKOK', '·', 'EST. 2009', '·', 'LGBTQ+ FRIENDLY', '·', 'OPEN NIGHTLY', '·'],

    promo_eyebrow: 'LIMITED TONIGHT',
    promo_title: 'TONIGHT\'S\nDEALS',
    promo_happy_tag: 'HAPPY HOUR',
    promo_happy_title: 'COCKTAILS 2-FOR-1',
    promo_happy_detail: 'MON–THU · 20:00–22:00',
    promo_happy_desc: 'Signature cocktails at half the price. Start your night right.',
    promo_happy_cta: 'BOOK A TABLE',
    promo_fri_tag: 'FRIDAY SPECIAL',
    promo_fri_title: 'FREE SHOT ON ENTRY',
    promo_fri_detail: 'EVERY FRI · WITH TABLE BOOKING',
    promo_fri_desc: 'Reserve your table before midnight and get a welcome shot on us.',
    promo_fri_cta: 'RESERVE NOW',
    promo_wknd_tag: 'WEEKEND VIBES',
    promo_wknd_title: 'BOTTLE PACKAGE',
    promo_wknd_detail: 'FRI–SAT · FROM ฿3,500',
    promo_wknd_desc: 'Premium spirit + mixer + reserved table for 4. Limited slots nightly.',
    promo_wknd_cta: 'GET THE DEAL',

    // Promos
    promo1_tag: 'HAPPY HOUR',
    promo1_title: 'Chang 3 Get 1 Free',
    promo1_detail: '15:00–20:00 · DAILY',
    promo1_desc: 'Buy 3 bottles of Chang beer, get 1 free — start the night right.',
    promo1_cta: 'BOOK A TABLE',
    promo2_tag: 'HAPPY HOUR',
    promo2_title: 'Singha Lite 4 for ฿299',
    promo2_detail: '15:00–20:00 · DAILY',
    promo2_desc: 'Get 4 bottles of Singha Lite for only ฿299. Unbeatable value.',
    promo2_cta: 'RESERVE NOW',
    promo3_tag: 'WEDNESDAY SPECIAL',
    promo3_title: 'Draft Chang 3+1 Free',
    promo3_detail: 'WED · BEFORE MIDNIGHT',
    promo3_desc: 'Buy 3 glasses of draft Chang, get 1 free — Wednesday done right.',
    promo3_cta: 'GET THE DEAL',
    promo4_tag: 'WEDNESDAY SPECIAL',
    promo4_title: 'Chang Tower 2+1 Free',
    promo4_detail: 'WED · ALL NIGHT',
    promo4_desc: 'Buy 2 Chang Towers, get 1 free. Go big on Wednesday.',
    promo4_cta: 'GET THE DEAL',
    promo5_tag: 'EVERYDAY',
    promo5_title: 'Paladin Prosecco 2 for ฿3,500',
    promo5_detail: 'DAILY · WHILE STOCKS LAST',
    promo5_desc: 'Two bottles of Paladin Prosecco for ฿3,500 — celebrate every night.',
    promo5_cta: 'RESERVE NOW',
    promo6_tag: 'BIRTHDAY PRIVILEGE',
    promo6_title: '10% OFF on Your Birthday',
    promo6_detail: 'SHOW YOUR ID · ANY DAY',
    promo6_desc: 'Show your ID on your birthday and get 10% off, on us. 🎂',
    promo6_cta: 'BOOK YOUR NIGHT',

    singers_eyebrow: 'THE VOICES OF THE NIGHT',
    singers_title: 'RESIDENT\nSINGERS',
    singers_book: 'BOOK THIS NIGHT →',
    lineup_sub: 'LIVE PERFORMANCES EVERY NIGHT · WHITE RABBIT BAR',
    events_h1: 'EVENTS',

    reviews_eyebrow: 'WORD ON THE STREET',
    reviews_title: 'WHAT THEY\nSAY',
    reviews_count: '200+ REVIEWS',

    map_eyebrow: 'FIND US',
    map_title: 'COME\nFIND US',
    map_address_label: 'ADDRESS',
    map_hours_label: 'HOURS',
    map_transit_label: 'GET THERE',
    map_address_value: 'On Silom Road, just before Soi 2\nBangkok 10500, Thailand',
    map_hours_value: 'Daily 15:00–LATE',
    map_transit_value: 'BTS Sala Daeng (Exit 3)\n3 min walk, on Silom Road before Soi 2',
    map_open_maps: 'OPEN IN GOOGLE MAPS ↗',
    map_book: 'BOOK A TABLE →',

    // Reserve page
    reserve_eyebrow: 'THE PORTAL',
    reserve_title: 'BOOK\nYOUR TABLE',
    reserve_subtitle: 'Fill in the form — or reach us instantly via LINE or phone. We\'ll confirm within 24 hours.',
    reserve_line_btn: 'LINE US',
    reserve_call_btn: 'CALL US',
    reserve_or: 'OR FILL THE FORM',
    reserve_name: 'FULL NAME',
    reserve_email: 'EMAIL',
    reserve_phone: 'PHONE',
    reserve_date: 'DATE',
    reserve_guests: 'GUESTS',
    reserve_event: 'EVENT',
    reserve_notes: 'NOTES',
    reserve_notes_ph: 'Special requests, occasions...',
    reserve_submit: 'CONFIRM BOOKING →',
    reserve_walkin: 'WALK-INS WELCOME · TABLE SERVICE AVAILABLE',
    reserve_confirmed_title: 'ACCESS\nCONFIRMED',
    reserve_confirmed_msg: 'WE\'VE RECEIVED YOUR REQUEST FOR',
    reserve_confirmed_body: 'Our team will confirm your booking at',
    reserve_back: '← BACK TO THE SURFACE',
    reserve_guest_singular: 'GUEST',
    reserve_guest_plural: 'GUESTS',

    // FAQ
    faq_eyebrow: 'GOT QUESTIONS?',
    faq_subtitle: 'Frequently asked questions — if you need more help, reach us via LINE or email below.',
    faq_still: 'STILL HAVE QUESTIONS?',
    faq_contact_sub: 'Contact us directly',

    // Contact
    contact_eyebrow: 'REACH OUT',
    contact_title: 'CONTACT\nUS',

    // Footer
    footer_tagline: 'FOLLOW THE WHITE RABBIT\nDOWN THE HOLE.',
    footer_contact: 'CONTACT',
    footer_hours: 'HOURS',
    footer_copy: '© 2026 WHITE RABBIT BAR. ALL RIGHTS RESERVED.',

    // Footer address & hours
    footer_address: 'ON SILOM ROAD, BEFORE SOI 2, BANGKOK 10500',
    footer_hours_1_day: 'DAILY',
    footer_hours_1_time: '15:00–LATE',
    footer_hours_2_day: '',
    footer_hours_2_time: '',
    footer_hours_3_day: '',
    footer_hours_3_time: '',

    // Contact page
    contact_phone_label: 'PHONE',
    contact_phone_cta: 'CALL NOW',
    contact_line_label: 'LINE',
    contact_line_cta: 'OPEN LINE',
    contact_location_label: 'LOCATION',
    contact_location_value: 'On Silom Road, just before Soi 2, Bangkok 10500',
    contact_location_cta: 'OPEN IN MAPS',
    contact_hours_title: 'OPENING HOURS',
    contact_hours_1_day: 'DAILY',
    contact_hours_1_time: '15:00 – LATE',
    contact_hours_2_day: '',
    contact_hours_2_time: '',
    contact_hours_3_day: '',
    contact_hours_3_time: '',
    contact_directions: 'DIRECTIONS',
    contact_follow: 'FOLLOW US',

    // Events page
    events_page_title: 'EVENTS &\nDJ NIGHTS',
    event1_desc: 'A journey through minimal techno and dark house. When the bass speaks, only the walls remain.',
    event2_desc: 'Ambient electronics mixed with underground beats. A meditation in motion.',
    event3_desc: 'When rhythm meets architecture. Industrial sounds in an intimate setting.',
    event4_desc: 'A Pride special. Celebrating identity through music that knows no boundaries.',
    event5_desc: 'Deep below the city. Music that vibrates through concrete and bone.',

    // FAQ questions & answers
    faq_q1: 'What are the opening hours?',
    faq_a1: 'Daily: 3 PM until late.',
    faq_q2: 'How do I get here?',
    faq_a2: 'We are on Silom Road, just before Soi 2. Take the BTS to Sala Daeng Station (Exit 3) and walk 3 minutes. You\'ll see us right on the main road.',
    faq_q3: 'Can I make a reservation?',
    faq_a3: 'Yes, table reservations are available and highly recommended. Book via our website.',
    faq_q4: 'Is there an entrance fee?',
    faq_a4: 'There is generally no entrance fee, but special events on certain nights may have one. Please check the events schedule.',
    faq_q5: 'Is the bar LGBTQ+ friendly?',
    faq_a5: 'Absolutely. White Rabbit is a safe, inclusive space for everyone regardless of gender or identity. All are welcome.',
    faq_q6: 'Is there live entertainment?',
    faq_a6: 'We host live singer and DJ performances every week. Check the Events page for the full schedule.',
    faq_q7: 'Is there parking available?',
    faq_a7: 'We do not have dedicated parking. We recommend taking the BTS or using Grab/Taxi.',
    faq_q8: 'Do you serve food?',
    faq_a8: 'We specialize in cocktails and beverages, with a selection of light snacks and bar bites available.',

    // Menu page
    menu_price_note: 'All prices in Thai Baht · Excluding 7% VAT and 10% Service Charge',
    menu_thai_label1: 'Som Tam · Grilled Beef · Grilled Squid · Yam Salad · Curry',

    sticky_book: 'BOOK NOW',
    scroll_label: 'SCROLL',
  },

  zh: {
    nav_menu: '菜单',
    nav_events: '活动',
    nav_gallery: '图库',
    nav_lineup: '演出阵容',
    nav_faq: '常见问题',
    nav_contact: '联系我们',
    nav_reserve: '预订',
    nav_book_now: '立即预订',

    hero_badge: '素隆路旁 · 曼谷 · 创立于 2009',
    hero_tagline: '跟随白兔，深入洞穴。',
    hero_book: '预订桌位 ↗',
    hero_events: '今晚阵容',

    events_eyebrow: '本月活动',
    events_title: '即将到来\n的夜晚',
    events_all: '全部活动 →',
    events_access: '进入 →',

    about_eyebrow: '场地介绍',
    about_title: '深入\n其中',
    about_body1: 'White Rabbit 不仅仅是一家酒吧——它是一次深入音乐、身份与奢华世界的旅程。坐落于曼谷最活跃的街区 Silom 的中心。',
    about_body2: '对所有人开放，不被任何人定义。',
    about_link: '探索空间 →',
    about_badge1: '素隆路主干道旁',
    about_badge2: '曼谷, 泰国',

    pride_headline_pre: '曼谷最',
    pride_highlight: '充满活力',
    pride_headline_post: '的 LGBTQ+ 空间',
    pride_sub: '欢迎所有人 · 尊重每一个人',

    marquee_items: ['WHITE RABBIT', '·', 'BEFORE SILOM SOI 2', '·', '曼谷', '·', '创立于 2009', '·', 'LGBTQ+ 友好', '·', '每晚营业', '·'],

    promo_eyebrow: '今晚限定',
    promo_title: '今晚\n优惠',
    promo_happy_tag: '欢乐时光',
    promo_happy_title: '鸡尾酒买一送一',
    promo_happy_detail: '周一至周四 · 20:00–22:00',
    promo_happy_desc: '招牌鸡尾酒半价，完美开启今晚。',
    promo_happy_cta: '预订桌位',
    promo_fri_tag: '周五特惠',
    promo_fri_title: '入场赠送免费Shot',
    promo_fri_detail: '每周五 · 提前预订桌位',
    promo_fri_desc: '在午夜前预订桌位，即可获得欢迎Shot。',
    promo_fri_cta: '立即预订',
    promo_wknd_tag: '周末派对',
    promo_wknd_title: '整瓶套餐',
    promo_wknd_detail: '周五至周六 · 起价 ฿3,500',
    promo_wknd_desc: '高级烈酒 + 混合饮料 + 4人预留桌位，每晚名额有限。',
    promo_wknd_cta: '获取优惠',

    // Promos
    promo1_tag: '欢乐时光',
    promo1_title: 'Chang 啤酒买3送1',
    promo1_detail: '15:00–20:00 · 每日',
    promo1_desc: '购买3瓶Chang啤酒，免费再得1瓶 — 畅快开启今晚。',
    promo1_cta: '预订桌位',
    promo2_tag: '欢乐时光',
    promo2_title: 'Singha Lite 4瓶仅 ฿299',
    promo2_detail: '15:00–20:00 · 每日',
    promo2_desc: '只需299泰铢，享4瓶Singha Lite，超值优惠不容错过。',
    promo2_cta: '立即预订',
    promo3_tag: '周三特惠',
    promo3_title: '生啤Chang 买3送1',
    promo3_detail: '周三 · 午夜前',
    promo3_desc: '购买3杯生啤Chang，免费再得1杯 — 周三最超值。',
    promo3_cta: '获取优惠',
    promo4_tag: '周三特惠',
    promo4_title: 'Chang Tower 买2送1',
    promo4_detail: '周三 · 全晚',
    promo4_desc: '购买2座Chang Tower，免费再得1座。周三豪爽畅饮。',
    promo4_cta: '获取优惠',
    promo5_tag: '每日优惠',
    promo5_title: 'Paladin Prosecco 2瓶 ฿3,500',
    promo5_detail: '每日 · 售完即止',
    promo5_desc: '3,500泰铢即可享2瓶Paladin Prosecco — 每晚都值得庆祝。',
    promo5_cta: '立即预订',
    promo6_tag: '生日特权',
    promo6_title: '生日当天享九折优惠',
    promo6_detail: '出示证件 · 任意日',
    promo6_desc: '生日当天出示身份证件，立享全单九折优惠。🎂',
    promo6_cta: '预订今晚',

    singers_eyebrow: '夜晚之声',
    singers_title: '驻场\n歌手',
    singers_book: '预订今晚 →',

    reviews_eyebrow: '顾客评价',
    reviews_title: '他们\n怎么说',
    reviews_count: '200+ 条评价',

    map_eyebrow: '找到我们',
    map_title: '来找\n我们',
    map_address_label: '地址',
    map_hours_label: '营业时间',
    map_transit_label: '交通',
    map_address_value: '素隆路，Soi 2 之前\n曼谷 10500, 泰国',
    map_hours_value: '每日 15:00 至深夜',
    map_transit_value: 'BTS Sala Daeng（3号出口）\n步行3分钟，在 Soi 2 前的主干道旁',
    map_open_maps: '在 Google 地图中打开 ↗',
    map_book: '预订桌位 →',

    // Reserve page
    reserve_eyebrow: '预订入口',
    reserve_title: '预订\n您的桌位',
    reserve_subtitle: '填写表格，或直接通过 LINE 或电话联系我们，我们将在 24 小时内确认。',
    reserve_line_btn: '联系 LINE',
    reserve_call_btn: '拨打电话',
    reserve_or: '或填写表格',
    reserve_name: '姓名',
    reserve_email: '电子邮件',
    reserve_phone: '电话',
    reserve_date: '日期',
    reserve_guests: '人数',
    reserve_event: '活动',
    reserve_notes: '备注',
    reserve_notes_ph: '特殊要求、纪念活动...',
    reserve_submit: '确认预订 →',
    reserve_walkin: '欢迎临时到访 · 提供桌边服务',
    reserve_confirmed_title: '预订\n已确认',
    reserve_confirmed_msg: '我们已收到您的预订请求',
    reserve_confirmed_body: '我们的团队将通过邮件确认您的预订',
    reserve_back: '← 返回首页',
    reserve_guest_singular: '位客人',
    reserve_guest_plural: '位客人',

    // FAQ
    faq_eyebrow: '有问题吗？',
    faq_subtitle: '常见问题解答 — 如需更多帮助，请通过下方的 LINE 或电子邮件联系我们。',
    faq_still: '还有问题？',
    faq_contact_sub: '直接联系我们',

    // Contact
    contact_eyebrow: '联系我们',
    contact_title: '联系\n我们',

    // Footer
    footer_tagline: '跟随白兔，深入洞穴。',
    footer_contact: '联系方式',
    footer_hours: '营业时间',
    footer_copy: '© 2026 WHITE RABBIT BAR. 版权所有。',

    // Footer address & hours
    footer_address: '素隆路，Soi 2 之前，曼谷 10500',
    footer_hours_1_day: '每日',
    footer_hours_1_time: '15:00 至深夜',
    footer_hours_2_day: '',
    footer_hours_2_time: '',
    footer_hours_3_day: '',
    footer_hours_3_time: '',

    // Contact page
    contact_phone_label: '电话',
    contact_phone_cta: '立即拨打',
    contact_line_label: 'LINE',
    contact_line_cta: '打开 LINE',
    contact_location_label: '位置',
    contact_location_value: '素隆路，Soi 2 之前，曼谷 10500',
    contact_location_cta: '在地图中打开',
    contact_hours_title: '营业时间',
    contact_hours_1_day: '每日',
    contact_hours_1_time: '15:00 至深夜',
    contact_hours_2_day: '',
    contact_hours_2_time: '',
    contact_hours_3_day: '',
    contact_hours_3_time: '',
    contact_directions: '导航',
    contact_follow: '关注我们',

    // Events page
    events_page_title: '活动\n& DJ 之夜',
    event1_desc: '一个庆祝身份、爱与自由的夜晚。White Rabbit 一年中最多彩、最电感的夜晚。',
    event2_desc: '服装、黑暗与低音——White Rabbit 将在曼谷变成最恐怖的酒吧，仅此一夜。',
    event3_desc: '在 White Rabbit 庆祝一年中最神奇的夜晚，节日鸡尾酒、现场表演与圣诞气氛。',
    event4_desc: '在曼谷最具标志性的酒吧迎接午夜倒计时，与 White Rabbit 大家庭一起迎接新年。',
    event5_desc: '深入城市地下。穿透混凝土与骨骼的震撼音乐。',

    // FAQ questions & answers
    faq_q1: '营业时间是什么时候？',
    faq_a1: '每日下午3点开始，营业至深夜。',
    faq_q2: '如何到达这里？',
    faq_a2: '我们位于素隆路主干道上，Soi 2 之前。乘坐 BTS 至 Sala Daeng 站（3号出口），步行约3分钟即可看到我们。',
    faq_q3: '可以预订座位吗？',
    faq_a3: '可以，我们提供桌位预订服务，强烈建议提前预订。您可以通过我们的网站或 LINE 官方账号进行预订。',
    faq_q4: '需要入场费吗？',
    faq_a4: '通常不收取入场费，但某些特别活动的夜晚可能会收费。请查看活动日程表。',
    faq_q5: '这里是 LGBTQ+ 友好场所吗？',
    faq_a5: '当然。White Rabbit 是一个对所有人开放的安全、包容空间，无论性别或身份认同。欢迎所有人。',
    faq_q6: '有现场表演吗？',
    faq_a6: '我们每周都有现场歌手和 DJ 表演。请查看活动页面了解完整日程。',
    faq_q7: '有停车位吗？',
    faq_a7: '我们没有专属停车位，建议乘坐 BTS 或使用 Grab/打车服务。',
    faq_q8: '提供食物吗？',
    faq_a8: '我们专注于鸡尾酒和饮品，同时提供各类小食和酒吧小吃。',

    // Menu page
    menu_price_note: '所有价格以泰铢计算 · 不含 7% VAT 及 10% 服务费',
    menu_thai_label1: '木瓜沙拉 · 烤牛肉 · 烤鱿鱼 · 泰式凉拌 · 咖喱',

    sticky_book: '立即预订',
    scroll_label: '向下滚动',

    // Weekly lineup
    lineup_eyebrow: '舞台',
    lineup_title: '每周\n演出阵容',
    lineup_sub: '每晚现场演出 · WHITE RABBIT BAR',
    lineup_book_prefix: '预订',

    // Events page
    events_h1: '活动',
    event_pride_desc: '一个庆祝身份、爱与自由的夜晚。White Rabbit 一年中最多彩、最电感的夜晚。',
    event_halloween_desc: '服装、黑暗与低音——White Rabbit 将在曼谷变成最恐怖的酒吧，仅此一夜。',
    event_xmas_desc: '在 White Rabbit 庆祝一年中最神奇的夜晚，节日鸡尾酒、现场表演与圣诞气氛。',
    event_nye_desc: '在曼谷最具标志性的酒吧迎接午夜倒计时，与 White Rabbit 大家庭一起迎接新年。',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const t = (key) => translations[lang]?.[key] ?? translations.en[key] ?? key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
